fix: ControlIHave and ControlIWant message types to bytes from string
Changed types of topicID and messageIDs from string to bytes in ControlIHave and ControlIWant messages.

This change is required due to this error message I saw:
```
iwant_msg.messageIDs.extend(msg_ids)
  UnicodeDecodeError: 'utf-8' codec can't decode byte 0x95
```

This happened because msg_ids contained raw binary hashes (arbitrary bytes), and when extending a repeated string field, Python's protobuf tries to decode them as UTF-8.